import Head from "next/head";
import type { NextPage } from "next";
import { NavigationBar } from "../components";
import { HomePageContent } from "../subsets";
import { Box, CssBaseline, createTheme, ThemeProvider } from "@mui/material";

const theme = createTheme({
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        body: {
          margin: 0,
        },
      },
    },
  },
});

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Dental Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />

      <main>
        <NavigationBar />
        <HomePageContent />
        <Box
          width="100vw"
          height="50vh"
          bgcolor="#eff6ff"
          position="fixed"
          top={0}
          zIndex={-1}
        ></Box>
      </main>
    </ThemeProvider>
  );
};

export default Home;
