#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ $(git rev-parse --abbrev-ref HEAD) != main ]]
then
    echo "This is a development branch"
    cd front && yarn lint-staged
else
    echo "This is main branch!!!"
fi
